INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(1,'SOLES','DOLARES',2.80);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(2,'DOLARES','SOLES',3.50);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(3,'SOLES','EURO',4.30);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(4,'EURO','SOLES',2.30);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(5,'DOLARES','EURO',3.30);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(6,'EURO','DOLARES',3.90);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(7,'YENG','SOLES',1.90);